version: '4.0'

actions:
  # generate_dataset:
  #   run: ehrql:v1 generate-dataset analysis/dataset_definition_patients.py --output output/dataset_patients.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       dataset: output/dataset_patients.csv.gz

  generate_dataset_preg_2024_11_01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_pregnancy.py --output output/dataset_preg_2024_11_01.csv.gz -- --start_date 2024-11-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_preg_2024_11_01.csv.gz

  generate_dataset_preg_2025_11_01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_pregnancy.py --output output/dataset_preg_2025_11_01.csv.gz -- --start_date 2025-11-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_preg_2025_11_01.csv.gz

  generate_dataset_practices:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_practices.py --output output/dataset_practices.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_practices.csv.gz
  
  generate_patient_dataset_2024_02_01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_patients.py --dummy-tables dummy_tables --output output/dataset_patients_2024-02-01.csv.gz -- --start_date 2024-02-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients_2024-02-01.csv.gz
  generate_patient_dataset_2024_03_01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_patients.py --dummy-tables dummy_tables --output output/dataset_patients_2024-03-01.csv.gz -- --start_date 2024-03-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients_2024-03-01.csv.gz
