version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_patients.py --output output/dataset_patients.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients.csv.gz

  generate_dataset_practices:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_practices.py --output output/dataset_practices.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_practices.csv.gz

  # loop the same dataset definition for each specific month
  generate_patient_dataset_2024_02_01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_patients_monthly.py
      --output output/dataset_patients_2024-02-01.csv.gz 
      -- 
      --start_date 2024-02-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients_2024-02-01.csv.gz
  generate_patient_dataset_2024_03_01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_patients_monthly.py
      --output output/dataset_patients_2024-03-01.csv.gz 
      -- 
      --start_date 2024-03-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients_2024-03-01.csv.gz
  
  # first-try: not working
  # generate_patient_dataset_monthly:
  #   for_each:
  #     start_date: ["2024-02-01", "2024-03-01", "2024-04-01"]
  #     run: ehrql:v1 generate-dataset analysis/dataset_definition_patients_monthly.py 
  #       --output output/dataset_patients_{{ start_date }}.csv.gz
  #       --
  #       --start_date {{ start_date }}
  #     outputs:
  #       highly_sensitive:
  #         dataset: output/dataset_patients_{{ start_date }}.csv.gz