version: '4.0'

actions:
  # generate_dataset:
  #   run: ehrql:v1 generate-dataset analysis/dataset_definition_patients.py --output output/dataset_patients.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       dataset: output/dataset_patients.csv.gz

  generate_dataset_preg:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_pregnancy.py --output output/dataset_preg.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_preg.csv.gz

  generate_dataset_practices:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_practices.py --output output/dataset_practices.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_practices.csv.gz
  
  generate_patient_dataset_2024_02_01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_patients.py --dummy-tables dummy_tables --output output/dataset_patients_2024-02-01.csv.gz -- --start_date 2024-02-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients_2024-02-01.csv.gz
  generate_patient_dataset_2024_03_01:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_patients.py --dummy-tables dummy_tables --output output/dataset_patients_2024-03-01.csv.gz -- --start_date 2024-03-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients_2024-03-01.csv.gz

  debug_generate_patient_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_patients.py --dummy-tables dummy-folder --output output/dataset_patients_debug.csv.gz -- --start_date 2024-02-01
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients_debug.csv.gz

  # action pending discussion - combine monthly tables - may need to add "needs: action name"
  # combine_monthly_patient_gz:
  #   run: python:v2 analysis/preprocess_combine_gz.py --output output/dataset_patients_combined.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       dataset: output/dataset_patients_combined.csv.gz
